---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baxiang.
--- DateTime: 2020/11/10 12:11 上午
---

local BasePlugin   = require "kong.plugins.base_plugin"

local HelloWorldHandler    = BasePlugin:extend()

HelloWorldHandler.VERSION  = "1.0.0"
HelloWorldHandler.PRIORITY = 10


function HelloWorldHandler:access(config)
    -- 如果Header中不包含kong字段, 提示出错
    if kong.request.get_header("kong") == nil then
        return kong.response.exit(403, "请求拒绝", {
            ["Content-Type"] = "text/plain",
        })
    end
    -- 增加请求参数,设置常量
    kong.service.request.add_header("x-kong-plugin", "hello kong")
    -- 增加请求参数,设置插件参数
    kong.service.request.add_header("x-kong-key", config.header_key)
    -- 打印日志位置: /usr/local/kong/logs/error.log
    kong.log(config.header_key)
end

function HelloWorldHandler:header_filter(config)
    -- 向客户端返回时, 添加header参数

    kong.response.set_header("x-kong-token", kong.request.get_header("kong"))
end


return HelloWorldHandler
