---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baxiang.
--- DateTime: 2020/11/10 12:12 上午
---

local typedefs = require "kong.db.schema.typedefs"
-- 定义输入类型为 字符串 数组, 意为可以输入多个字符串

return {
    name = "hello-kong",
    fields = {
        { protocols = typedefs.protocols_http },
        { config = {
            type = "record",
            fields = {
                { header_key = { type = "string",default ="kong" }, },
            },
        },
        },
    },
}
