---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baxiang.
--- DateTime: 2020/11/8 3:34 下午
---

--- 配置文件

return {
    no_consumer = true,
    fields = {
        auth_server_url = {type = "url", required = true},
    }
}